name       : proton-python-client
version    : 0.7.1
release    : 2
source     :
    - https://github.com/ProtonMail/proton-python-client/archive/refs/tags/0.7.1.tar.gz : 88d2546a922d9053988b5e1863bf6cf965e97b4c643cd879f16bb3f0b5f02b5e
license    : GPL-3.0-or-later
component  : network.clients
summary    : Python Proton client module.
description: |
    Python Proton client module.
builddeps  :
    - python-bcrypt
    - python-gnupg
    - python-openssl
    - python-requests
rundeps    :
    - dnspython
    - python-bcrypt
    - python-gnupg
    - python-openssl
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
